In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Extrair a diagonal principal:

In [3]:
matriz.diagonal()

array([1, 5, 9])

Extrair a diagonal acima da principal:

In [4]:
matriz.diagonal(1)

array([2, 6])

Extrair a diagonal abaixo da principal:

In [5]:
matriz.diagonal(-1)

array([4, 8])

In [6]:
matriz.diagonal(2)

array([3])

In [7]:
matriz.diagonal(-2)

array([7])

CÁLCULO DA MATRIZ INVERSA:

In [8]:
np.linalgS.inv(matriz)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

**NÃO CALCULA A MATRIZ INVERSA:**

In [9]:
np.invert(matriz)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

NUMPY 4

In [10]:
vetor= np.array([1,2,3,4,5,6])
print(vetor)


[1 2 3 4 5 6]


In [14]:
print(np.where(vetor>3))

(array([3, 4, 5], dtype=int64),)
